### ISSUE TITLE
Choose backend

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/weaverbird#46]
As a query designer, I can choose to generate queries on different backends. We could imagine the following ones:

- `mongo 3.6` + `python postprocess`
- `mongo 4` + `python postprocess`
- `pandas only`
- `sql` + `python postprocess`

We don't want here to implement all those backends, just to prepare the code (and the UI) architecturally to support multiple backends.

**Comment by davinov** [comment]
A first back-end selector has been implemented in the playground :)
(However, no mixed-backend for now)
