### ISSUE TITLE
Common organization for backends for simpler contribution

### ISSUE THREAD

**Issue by davinov** [ToucanToco/weaverbird#913]
With the impulse of #912, we'd like to simplify the contributions around backends, and make it clearer what is and is not implemented in each backend.

This covers to problems today:
- files organization: today each backend can have is own subfolder or way to organize things. This is not coherent and does not guide any new developer on how to properly make a backend. Also, if a new step is created, it's unclear how to track its implementation across every backend.
- testing: today each backend must implement its own test suite. Some are kind-of e2e (pandas) but hard to read and reuse, while translators ones (mongo) only test the output query, without any warranty that such queries will lead to the expected transformation.

## Files organization

For this purpose, I imagine we have a set of backends we don't have as of today:
- a vega executor, which is a front-end executor
- a mongo translator back-end side (python)

This is a way to see if the architecture scales correctly with the four options:
- a mongo translator in python
- a mongo translator in typescript
- a vega executor in typescript
- a pandas executor in python

```
backends/
  core/
    mongo-js/
    mongo-py/
    pandas/
    vega/
  steps/
    filter/
      filter.mongo.ts
      filter.mongo.py
      filter.pandas.py
      filter.vega.ts
```

Advantages of this architecture:
- easy to spot which steps are implemented by which backend
- combination of step name + backend + extension makes them easy to grep

In the core folder, we should find a entry point for each backend, than would handle:
- importing all the steps implementations (ideally with a glob/regex, `like steps/*/*.mongo.ts`)
- handling the logic of putting steps together
- optionally some _after-translation_ logic, such as simplifying a query output to make it more readable
- exposing a standard API with pipeline steps as input

Action plan:

- [x] reorganize the pandas executor
- [ ] reorganize the mongo translator

## Testing

To avoid recreating test cases for each new backend, I suggest we declare input/outputs once and for all and reuse them for all backends.

For this, we need a way to declare test cases that could be read and executed by each backend.
One test case is constituted of:
- the input data
- the expected output data
- the configuration of the step

We can either group them in one file with a structure, or split them into multiple ones.
If we want to use CSV to describe data, we will nee to have separate files. For JSON, it could seem not necessary but I think it'll be easier to read and maintain if we still have separate files.

:warning: Data types can be lost along the way if stored in CSV or JSON (for example dates are not unspported in JSON).
To mitigate this, we could use the https://specs.frictionlessdata.io/table-schema/ format, which is still easy to read, and allow specifying data types. 

Here would be an example with two test cases for the filter step:
```
backends/
  steps/
    filter/
      tests/
       simple-filtering/
         simple-filtering.input.json
         simple-filtering.output.json
         simple-filtering.config.json
       dates-filtering/
         dates-filtering.input.json
         dates-filtering.output.json
         dates-filtering.config.json
```

The config.json file should contain:
- `description` a readable sentence describing the test
- `step` the configuration of the step to test 
- `skip` a list of backends identifiers known not support the test

:information_source: These cases could also be useful for documentation.

Each backend should provide a way to execute a test case. That could be done in their core folder.
For translators, that engine should spawn a version of the associated service (e.g. a mongo container). We do something similar in https://github.com/ToucanToco/toucan-connectors.

If we need some tests specific for a backend, or for a succession of steps, we could store them in the backends/core/... folder. (I can only think of tests for the _after-translation_ simplification logic for now).

Action plan:

- [x] create a few test cases for one step
- [x] create the test runner for the pandas executor
- [ ] create the test runner for the mongo translator
- [x] ensure these tests are run by GitHub actions (CI)
- [ ] add test cases for each type of step

Questions:
- What about different versions of mongo? I suggest we should have one backend per version, but they can share a lot code by importing the steps files, except for the one that are not supported. Alternatively, I think we could also only support the last versions of mongo (I'm not sure we have usage for the older ones).

**Comment by austil** [comment]
> For this purpose, I imagine we have a set of backends we don't have as of today:
> -  a vega executor, which is a front-end executor
> -  a mongo translator back-end side (python)

Note : in the same paragraph, we are mixing Weaverbird frontend (the UI Components) & backend (the pipeline compilers or interpreters) division with our own product (Toucan) frontend (the JS web client) & backend (the Python server api) division.

**Comment by davinov** [comment]
Good point. That's why the term back-end feels a bit too vague to me. It can either be used as a synonym of "server-side" (which could also be javascript) or opposed as "UI" (which could be executed also in a browser).

**Comment by hachichaud** [comment]
Hello :) 
I'm all for restructuring so the project so it's easier to contribute.
One thing I don't understand : if executors and translators are different, why group them together ?
Reading the file structure : 

```
filter/
      filter.mongo.ts
      filter.mongo.py
      filter.pandas.py
      filter.vega.ts
```

It's hard to know which is which. What's the point of mixing the two? 
I'm guessing translators and executors aren't used in the same way.

**Comment by davinov** [comment]
That's a good question!
Executors and translators are not _so_ different, they are both implementations based on the pipeline steps language.
Where they differ is how they are used:
- a translator will output a query (string, or literal object) ; you'll need an actual DB to run it
- an executor will output a function ; you'll only need an execution context (i.e. `python`, or a browser for js) to run it
Also, after discussing with Pierre, we only foresee 2 executors, so there is little chance that we would have 2 same identifiers for one executor and one translator.

So you're right: the difference between the two should be taken so strongly in the description of the issue. => Correcting it.

**Comment by hachichaud** [comment]
If they are used differently, and don't output the same thing, I still don't understand why we would want to mix the two.
Isn't it going to cause confusion and force us to create a special case for the executors ?

**Comment by davinov** [comment]
I'm closing this as done :tada: 
Today, we do have common fixtures for all our backends, and they all share common models that describe all the possible steps :+1: 

We did got into the javascipt backends for now - we may reopen this route one day... we'll see!
